// src/components/MainContent/MainContent.vue
<template>
<div>
    <div class="row areaTitle" v-if="forecast.daily != undefined">
        <div class="col-sm-12 text-center">
            <h2>{{forecast.area.name}}, {{forecast.area.country}}
                <button type="button" v-if="favorited" @click="toggleFav()" class="btn btn-default btnFav">
                    <i class="bi bi-heart-fill"></i>
                    <!-- Es favorito -->
                </button>
                <button type="button" v-if="!favorited" @click="toggleFav()" class="btn btn-default btnFav">
                    <i class="bi bi-heart"></i>
                    <!-- No es favorito -->
                </button>
            </h2>
            
        </div>
    </div>
    <div class="row areaTitle" v-if="forecast.daily != undefined">
        <div class="col px-0" v-for="weather in forecast.daily.slice(0,7)" :key="weather.dt"> 
            <WeatherCard :dailyForecast="weather" :forecast="forecast"/>
        </div>
    </div>
</div>
</template>

<script>
import WeatherCard from '../WeatherCard/WeatherCard.vue'
export default {
    name: 'MainContent',
    components: {
        WeatherCard
    },
     props: {forecast: {}},
    data(){
        return{
            dataLoaded: false,
            favorited: false,
            favoriteCities: [],
        }
    },
    created(){
         this.favoriteCities = JSON.parse(localStorage.getItem('favoritedAreas')) ?? [];
    },
    methods:{
        openDetail(dateString){
            var hourlyDetail = this.forecast.hourly.filter(f => this.$moment(new Date(f.dt * 1000)).format('YYYY-MM-DD HH:mm:ss').includes(dateString));
            console.log(hourlyDetail);
        }, 
        toggleFav(){
            if(!this.favorited){
                this.favoriteCities.push(this.forecast.area);
                localStorage.setItem('favoritedAreas', JSON.stringify(this.favoriteCities));
            }else{
                this.favoriteCities = this.favoriteCities.filter(f => f.name !== this.forecast.area.name || f.country !== this.forecast.area.country);
                localStorage.setItem('favoritedAreas', JSON.stringify(this.favoriteCities));
            }
            this.favorited = !this.favorited;
            console.log('desde main content: l.59', this.favoriteCities)
            this.$emit('sendFavorites',this.favoriteCities);
        },
        checkIfFavorited(){
            this.favorited = this.favoriteCities.some(s => s.name === this.forecast.area.name && s.country === this.forecast.area.country);
        }
    },
    watch:{
        forecast(oldVal, newVal){
            if(oldVal !== newVal){
                this.checkIfFavorited();
            }
        }
    }
}
</script>

<style>
.areaTitle{
    margin-top: 20px;
}
.btnFav{
    color:red !important;
    transition: all .2s ease-in-out;
}

.btnFav:active{
    transform: scale(1.1);
}

.favorites{
    margin-top: 10px;
}

.weatherDescription{
    margin-top: 5px;
}
</style>

// src/app/components/main-content/main-content.component.ts
import { DatePipe } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { BsModalService } from 'ngx-bootstrap/modal';
import { Area } from 'src/app/models/area';
import { Forecast } from 'src/app/models/forecast';
import { ForecastHourlyDetailComponent } from '../modals/forecast-hourly-detail/forecast-hourly-detail.component';
import { WeatherDetailCardComponent } from '../weather-detail-card/weather-detail-card.component';

@Component({
  selector: 'app-main-content',
  templateUrl: './main-content.component.html',
  styleUrls: ['./main-content.component.css']
})
export class MainContentComponent implements OnInit {
  @Input() forecast!: Forecast;
  dataLoaded = false;
  favorited: boolean;
  favoriteCities: Area[];
  constructor(public datepipe: DatePipe, public dialog: BsModalService) { }

  ngOnInit(): void {
    this.favoriteCities = JSON.parse(localStorage.getItem('favoritedAreas')!) ?? []
  }

  ngOnChanges():void{
    this.dataLoaded = (typeof this.forecast !== "undefined");
    this.checkIfFavorited();
  }
 

  toggleFav(){
    if(!this.favorited){
      this.favoriteCities.push(this.forecast.area);
      localStorage.setItem('favoritedAreas', JSON.stringify(this.favoriteCities));
    }else{
      this.favoriteCities = this.favoriteCities.filter(f => f.name !== this.forecast.area.name || f.country !== this.forecast.area.country);
      console.log(this.favoriteCities);
      localStorage.setItem('favoritedAreas', JSON.stringify(this.favoriteCities));
    }
    this.favorited = !this.favorited;
  }

  checkIfFavorited(){
    if(this.dataLoaded){
      this.favorited = this.favoriteCities.some(s => s.name === this.forecast.area.name && s.country === this.forecast.area.country);
    }
  }

  refreshWeather(forecast:Forecast){
    
    this.forecast = forecast;
    this.dataLoaded = true;
    this.checkIfFavorited();
  }

  openDetail(date: string){
    var hourlyDetail = this.forecast.hourly.filter(f => this.datepipe.transform(f.dt * 1000, 'yyyy-MM-dd HH:mm:ss')?.includes(date))
    var initialState = {
      dayInfo: hourlyDetail
    }
    this.dialog.show(ForecastHourlyDetailComponent,{
      initialState
    })
  }

}

<div class="row areaTitle" *ngIf="dataLoaded">
    <div class="col-sm-12 text-center">
        <h2>{{forecast.area.name}}, {{forecast.area.country}}
            <button type="button" *ngIf="favorited" (click)="toggleFav()" class="btn btn-default btnFav">
                <i class="bi bi-heart-fill"></i>
              </button>
              <button type="button" *ngIf="!favorited" (click)="toggleFav()" class="btn btn-default btnFav">
                <i class="bi bi-heart"></i>
              </button>
        </h2>
        
    </div>
</div>
<div class="row weatherForecast" *ngIf="dataLoaded">
    <div class="col px-0" *ngFor="let forecast of forecast.daily.slice(0,7)">
       <app-weather-card [dailyForecast]="forecast" (sendDate)="openDetail($event)"></app-weather-card>
    </div>
</div>
<hr/>
<div class="row favorites">
    <div class="col-sm-2">
        <app-favorites-list [favoriteCities]="favoriteCities" (setForecast)="refreshWeather($event)"></app-favorites-list>
    </div>
</div>
