// src/components/WeatherDetailCard/WeatherDetailCard.vue
<template>
    <div>
  <b-card class="align-left weatherCard">
    <h6 class="card-title">{{hourInfo.dt * 1000 | moment('MMM DD')}} <span class="hour">{{hourInfo.dt * 1000 | moment('HH:mm')}}</span></h6>
      <div id="icon"><img id="wicon" :src="'http://openweathermap.org/img/w/' + hourInfo.weather[0].icon + '.png'" alt="Weather icon"></div>
      <div><span class="maxTemp">{{hourInfo.temp}}°C</span></div>
      <div class="weatherDetails">
          <div>Wind: {{hourInfo.windSpeed}} km/h</div>
          <div>Humidity: {{hourInfo.humidity}}%</div>
       </div>
       <h6 class="weatherDescription">{{hourInfo.weather[0].main}}</h6>
  </b-card>
</div>
</template>

<script>
export default {
  name: 'WeatherCardDetail',
  components: {
  },
  props:{
      hourInfo: {}
  }
}
</script>

<style>
.dayPart{
    color:#00bed4;
    margin-bottom: 0;
}

.maxTemp{
    font-size: 30px;
    color: black;
}

.minTemp{
    font-size: 20px;
    color:gray;
    vertical-align: top;
}

.weatherDetails{
    color:gray;
    font-size: 12px;
}

.hour{
    color: #d13848
}
</style>

// src/app/components/weather-detail-card/weather-detail-card.component.ts
import { DatePipe } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { DetailForecast } from 'src/app/models/detail-forecast';

@Component({
  selector: 'app-weather-detail-card',
  templateUrl: './weather-detail-card.component.html',
  styleUrls: ['./weather-detail-card.component.css']
})
export class WeatherDetailCardComponent implements OnInit {
 @Input() hourInfo: DetailForecast
  constructor(public datepipe: DatePipe) { }

  ngOnInit(): void {
    console.log(this.hourInfo);
  }
  formatDate(dt:number){
    return this.datepipe.transform(new Date(dt*1000),'MMM dd')!.toUpperCase()
  }
  formatHour(dt:number){
    return this.datepipe.transform(new Date(dt*1000),'HH:mm')!.toUpperCase()
  }
}

<div class="card weatherCard" >
    <div class="card-body">
      <h6 class="card-title">{{formatDate(hourInfo.dt)}} <span class="hour">{{formatHour(hourInfo.dt)}}</span></h6>
      <div id="icon"><img id="wicon" [src]="'http://openweathermap.org/img/w/' + hourInfo.weather[0].icon + '.png'" alt="Weather icon"></div>
      <div><span class="maxTemp">{{hourInfo.temp}}°C</span></div>
      <div class="weatherDetails">
          <div>Wind: {{hourInfo.wind_speed}} km/h</div>
          <div>Humidity: {{hourInfo.humidity}}%</div>
       </div>
       <h6 class="weatherDescription">{{hourInfo.weather[0].main}}</h6>
      
    </div>
  </div>
