// src/components/NavBar/NavBar.vue
<template>
  <div>
  <b-navbar toggleable="lg" type="dark" class="myNav" variant="info">
    <b-navbar-brand href="#">Weather App - Trimble</b-navbar-brand>
      <!-- Right aligned nav items -->
      <b-navbar-nav class="ml-auto">
        <b-nav-form>
          <b-form-input size="sm" class="mr-sm-2"  v-model="area" placeholder="Search by city/zip code"></b-form-input>
          <b-button size="sm" class="my-2 my-sm-0" v-on:click="searchArea" type="button">Search</b-button>
        </b-nav-form>
      </b-navbar-nav>
  </b-navbar>
</div>
</template>

<script>
// import WeatherService from '../../services/WeatherService'

export default {
 
  name: 'NavBar',
  components: {
    
  },
  data() {
    return{
      area: '',  
      weatherApi : 'http://localhost:5170/api/WeatherForecast/',
      geolocationApi: 'http://localhost:5170/api/Geolocation/',
      areaInfo: {}
      }
  },
  methods: {
    searchArea(){
      var apiCall = this.geolocationApi + `GetCityLatLng?cityName=${this.area}`
      this.$http.get(apiCall).then(response => {
      if(response.body.length == 0){
        this.searchZipCode(this.area);
      }else{
        var areaFound = response.body.find(f => f.name == this.area);
        this.areaInfo = areaFound;
        this.searchWeather(areaFound);
      }
  
    }, response => {
      console.log(response)
    });
    },
    searchZipCode(){
      var apiCall = this.geolocationApi + `GetZipCodeLatLng?zipCode=${this.area}`
            this.$http.get(apiCall).then(response => {
              this.areaInfo = response.body;
              this.searchWeather(response.body);
          }, response => {
            console.log(response)
          });
    },
    searchWeather(latlng){
      var params = {lat: latlng.lat, lng: latlng.lon}
       var apiCall = this.weatherApi + `GetWeatherByArea`
       console.log(latlng)
      this.$http.post(apiCall,params).then(response => {
        console.log(response.body);
        if(response.body.length == 0){
          console.log('Empty Set')
        }else{
          response.body.area = this.areaInfo;
          this.$emit('sendForecast',response.body)
        }
  
    }, response => {
      console.log(response)
    });
    }

  }
}
</script>

<style>
.myNav{
    background-color: #d13848 !important;
}
</style>

// src/app/components/nav-bar/nav-bar.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Area } from 'src/app/models/area';
import { Forecast } from 'src/app/models/forecast';
import { LatLng } from 'src/app/models/lat-lng';
import { GeolocationService } from 'src/app/services/geolocation.service';
import { WeatherService } from 'src/app/services/weather.service';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
  searchForm: FormGroup;
  area: Area;
  @Output() setWeather: EventEmitter<Forecast> = new EventEmitter();
  constructor(public weatherService: WeatherService, public geolocationService: GeolocationService) { }

  ngOnInit() {
    this.searchForm = new FormGroup({
      area: new FormControl({ value: '', disabled: false }, { validators: Validators.required }),
  });
  }

  searchArea(){
    if(this.searchForm.valid){
       var area:string = this.searchForm.controls["area"].value;
      this.geolocationService.getCityLatLng({cityName: area}).subscribe(res =>{
        if(res.length === 0){
          this.geolocationService.getZipCodeLatLng({zipCode: area}).subscribe(res =>{
              var latlng = new LatLng(res.lat, res.lon)
              this.area = res;
              console.log(res);
              this.searchWeather(latlng);
          }, error =>{
          }); 
        }else{
          var areaFound = res.find(f => area.toLowerCase() == f.name.toLowerCase());
          this.area = areaFound!;
          console.log(res);
           var latlng = new LatLng(areaFound!.lat, areaFound!.lon)
           this.searchWeather(latlng);
        }
      }, error =>{
      
      });
    }
  }

  searchWeather(latlng: LatLng){
    console.log(latlng)
    this.weatherService.getWeatherByArea(latlng).subscribe(res => {
      res.area = this.area;
      console.log(res);
      this.setWeather.emit(res);
    },error => {

    });
  }

}

<nav class="navbar navbar-light bg-light justify-content-between myNav">
    <a class="navbar-brand myNavTitle">Weather App - Trimble</a>
    <form class="form-inline" [formGroup]="searchForm" (ngSubmit)="searchArea()">
      <input class="form-control mr-sm-2" type="search" formControlName="area" placeholder="Search by city/zipcode" aria-label="Search">
      <button class="btn my-2 my-sm-0 myNavButton" id="button" type="submit" >Search</button>
    </form>
  </nav>
